-- FCB Distributor Allocation App — Seed Data
-- Run this AFTER schema.sql and functions.sql. Populates the distributor and
-- product lists using your actual current data (pulled from the "Inventory
-- for Sale" spreadsheet, 8/11/26 tab) so you can start using the app with
-- real products right away instead of a blank list.
--
-- Feel free to edit names/colors below before running, or clean up
-- afterwards directly in the Supabase table editor.

insert into distributors (name, color) values
  ('Matagrano', '#3fb950'),
  ('Saccani', '#d4a017'),
  ('Valleywide', '#388bfd'),
  ('Guardian', '#bc8cff'),
  ('Markstein', '#00b4d8'),
  ('Coast', '#f85149'),
  ('Superior', '#ff7b54')
on conflict (name) do nothing;

insert into products (name) values
  ('EUREKA STOUT - 1/2 bbl keg'),
  ('Capt. WC PALE ALE (Case - 6x4 - 16oz - Can)'),
  ('Capt. Pale Ale (Keg - 1/2 bbl)'),
  ('Capt. Pale Ale (Keg - 1/6 bbl)'),
  ('Capt. Hazy (Case - 6x4 - 16oz - Can)'),
  ('Capt. Hazy (Case - 12x - 19.2oz - Can)'),
  ('Capt. Hazy (Keg - 1/6 bbl)'),
  ('Capt. Hazy (Keg - 1/2 bbl)'),
  ('Capt. Hazy Imperial Punch (Case - 12x - 19.2oz - Can)'),
  ('Capt. Hazy Imperial Punch (Case - 6x4 - 16oz - Can)'),
  ('Capt. Hazy Imperial Punch (Keg - 1/2 bbl)'),
  ('Capt. Hazy Imperial Punch (Keg - 1/6 bbl)'),
  ('Hazy Beach (Keg - 1/2 bbl)'),
  ('Capt. WC IPA (Case - 6x4 - 16oz - Can)'),
  ('Capt. WC (Case - 12x - 19.2oz - Can)'),
  ('Town & City 16oz'),
  ('Capt. WC (Keg - 1/6 bbl)'),
  ('Capt. WC (Keg - 1/2 bbl)'),
  ('Illa Vanilla Milkshake IPA (6 pack 12oz box)'),
  ('Illa Vanilla Milkshake IPA (6 pack Mixed pack case)'),
  ('Illa Vanilla Milkshake IPA (Case 6x4 - 16oz Cans)'),
  ('Illa Vanilla Milkshake IPA (Keg - 1/2 bbl)'),
  ('Illa Vanilla Milkshake IPA (Keg - 1/6 bbl)'),
  ('Strawberry Milkshake IPA (Case 6x4 - 16oz Cans)'),
  ('Blueberry Illa (Case 6x4 - 16oz Cans)'),
  ('Strawberry Illa (Keg - 1/2 bbl)'),
  ('Juicy NE IPA (Case - 6x4 - 16oz - Can)'),
  ('Juicy NE IPA (Case - 12x - 19.2oz - Can)'),
  ('Juicy NE IPA (Keg - 1/6 bbl)'),
  ('Juicy NE IPA (Keg - 1/2 bbl)'),
  ('Mango Bomb NE IIPA Series (Case - 6x4 - 16oz - Can)'),
  ('Mango Bomb NE IIPA Series (Case - 12x - 19.2oz - Can)'),
  ('Mango Bomb NE IIPA (Keg - 1/6 bbl)'),
  ('Mango Bomb NE IIPA (Keg - 1/2 bbl)'),
  ('Nectarine Pie of the Tiger (Case - 6x4 - 16oz - Can)'),
  ('Nectarine Pie of the Tiger (Keg - 1/6 bbl)'),
  ('Nectarine Pie of the Tiger (Keg - 1/2 bbl)'),
  ('Peachy Vibes (Case - 4x6 - 12oz - Can)'),
  ('Peachy Vibes (Case - 12x - 19.2oz - Can)'),
  ('Peachy Vibes (Keg - 1/6 bbl)'),
  ('Peachy Vibes (Keg - 1/2 bbl)'),
  ('Beachy Vibes (keg - 1/6 bbl)'),
  ('Beachy Vibes (keg - 1/2 bbl)'),
  ('PRESS BOX PL BLONDE (keg - 1/6bbl)'),
  ('TEKO (Case - 4x6 - 12oz - Can)'),
  ('TEKO (Keg - 1/2 bbl)'),
  ('TEKO (Keg - 1/6 bbl)'),
  ('Spartan (cases - 12oz - cans)'),
  ('Cherry Blossom Sakura Chaya (cases - 16oz cans)'),
  ('Cherry Blossom Sakura Chaya (kegs - 1/6 bbl )'),
  ('Victory Vibes (Case - 4x6 - 12oz - Can)'),
  ('Victory Vibes (Case - 12x - 19.2oz - Can)'),
  ('Victory Vibes (Keg - 1/6 bbl)'),
  ('Victory Vibes (Keg - 1/2 bbl)'),
  ('The Hatchet - Apple Cider (Case 6x4 - 16 oz Cans)'),
  ('The Hatchet - Apple Cider (Keg - 1/6 bbl)'),
  ('The Hatchet - Apple Cider (Keg - 1/2 bbl)'),
  ('The Pitchfork - Pear Cider (Case 6x4 - 16 oz Cans)'),
  ('The Pitchfork - Pear Cider (Keg - 1/6 bbl)'),
  ('The Pitchfork - Pear Cider (Keg - 1/2 bbl)'),
  ('The Sickle - Pineapple Cider (Case 6x4 - 16 oz Cans)'),
  ('The Sickle - Pineapple Cider (Keg - 1/6 bbl)'),
  ('The Sickle - Pineapple Cider (Keg - 1/2 bbl)'),
  ('Guava Cider (Keg - 1/2 bbl)'),
  ('Guava Cider (Keg - 1/6 bbl)'),
  ('Big Daddy IPA (Case 4x6 - 12 oz Cans)'),
  ('Big Daddy IPA (Case 6x4 - 16 oz Cans)'),
  ('Big Daddy IPA (Case - 12x - 19.2oz - Can)'),
  ('Big Daddy IPA (Keg - 1/6 bbl)'),
  ('Big Daddy IPA (Keg - 1/2 bbl)'),
  ('Blind Tiger (Case 6x4 - 16 oz Cans)'),
  ('Blind Tiger (Keg - 1/2 bbl)'),
  ('Blind Tiger (Keg - 1/6 bbl)'),
  ('Mystic Haze IPA (Case 4x6 - 12 oz Cans)'),
  ('Mystic Haze IPA (Case 6x4 - 16 oz Cans)'),
  ('Mystic Haze IPA (Case - 12x - 19.2oz - Can)'),
  ('Mystic Haze (Keg - 1/6 bbl)(JUICY)'),
  ('Mystic Haze (Keg - 1/2 bbl)'),
  ('Prohibition (Case 4x6 - 12 oz Cans)'),
  ('Prohibition Red Ale (Keg 1/6bbl)'),
  ('Prohibition Red Ale (Keg 1/2 bbl)'),
  ('The Dopest (Case - 6x4 - 16oz - Can)'),
  ('The Dopest (Keg - 1/2 bbl)'),
  ('The Dopest (Keg - 1/6 bbl)'),
  ('FCB Can Tap Handle'),
  ('Speakeasy Tap Handle'),
  ('BPLB (cases - 6x4 -16 oz - cans)'),
  ('8 trill pills (cases - 6x4 - 16oz - cans)'),
  ('8 trill pills (kegs - 1/2 bbl)'),
  ('Dopetoberfest (cases - 6x4 - 16oz - cans)'),
  ('Dopetoberfest (kegs - 1/2bbls)'),
  ('Seltzer Batch #1 (kegs-1/2bbl)'),
  ('Tea Base (kegs- 1/2bbl)')
on conflict (name) do nothing;
